/* Generated by Yosys 0.58+86 (git sha1 8bc63ef6d, g++  -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "onehot2u2_decoder" *)
(* src = "MODEL/library_modules.v:70.1-108.10" *)
module \$paramod$a9c22756d9a8dd0110c8c717d10bd443a01d2637\onehot2u2_decoder (i_a_oh, i_b_oh, o_y_u2, o_overflow, o_err);
  (* src = "MODEL/library_modules.v:76.26-76.32" *)
  input [0:0] i_a_oh;
  wire [0:0] i_a_oh;
  (* src = "MODEL/library_modules.v:77.26-77.32" *)
  input [0:0] i_b_oh;
  wire [0:0] i_b_oh;
  (* src = "MODEL/library_modules.v:78.28-78.34" *)
  output [3:0] o_y_u2;
  wire [3:0] o_y_u2;
  (* src = "MODEL/library_modules.v:79.28-79.38" *)
  output o_overflow;
  wire o_overflow;
  (* src = "MODEL/library_modules.v:80.28-80.33" *)
  output o_err;
  wire o_err;
  (* src = "MODEL/library_modules.v:86.5-107.8" *)
  wire [31:0] _0_;
  (* src = "MODEL/library_modules.v:83.13-83.14" *)
  wire [31:0] i;
  (* src = "MODEL/library_modules.v:85.23-85.31" *)
  wire [1:0] i_onehot;
  (* src = "MODEL/library_modules.v:84.13-84.18" *)
  wire [31:0] posit;
  assign o_err = i_b_oh ? (* src = "MODEL/library_modules.v:97.17-97.36|MODEL/library_modules.v:97.13-104.20" *) i_a_oh : 1'h0;
  assign posit[0] = i_b_oh ? (* src = "MODEL/library_modules.v:97.17-97.36|MODEL/library_modules.v:97.13-104.20" *) _0_[0] : 1'h0;
  assign _0_[0] = ~(* src = "MODEL/library_modules.v:98.21-98.27|MODEL/library_modules.v:98.17-104.20" *) i_a_oh;
  assign _0_[31:1] = 31'h00000000;
  assign i = 32'd2;
  assign i_onehot = { i_b_oh, i_a_oh };
  assign o_overflow = 1'h0;
  assign o_y_u2 = { 3'h0, posit[0] };
  assign posit[31:1] = 31'h00000000;
endmodule

(* dynports =  1  *)
(* hdlname = "nand_gate" *)
(* src = "MODEL/library_modules.v:21.1-36.10" *)
module \$paramod\nand_gate\WIDTH=s32'00000000000000000000000000000100 (i_a, i_b, o_y, o_overflow, o_err);
  (* src = "MODEL/library_modules.v:25.35-25.38" *)
  input [3:0] i_a;
  wire [3:0] i_a;
  (* src = "MODEL/library_modules.v:26.35-26.38" *)
  input [3:0] i_b;
  wire [3:0] i_b;
  (* src = "MODEL/library_modules.v:27.35-27.38" *)
  output [3:0] o_y;
  wire [3:0] o_y;
  (* src = "MODEL/library_modules.v:28.35-28.45" *)
  output o_overflow;
  wire o_overflow;
  (* src = "MODEL/library_modules.v:29.35-29.40" *)
  output o_err;
  wire o_err;
  (* src = "MODEL/library_modules.v:32.17-32.26" *)
  wire [3:0] _0_;
  assign _0_[0] = i_a[0] &(* src = "MODEL/library_modules.v:32.17-32.26" *)  i_b[0];
  assign _0_[1] = i_a[1] &(* src = "MODEL/library_modules.v:32.17-32.26" *)  i_b[1];
  assign _0_[2] = i_a[2] &(* src = "MODEL/library_modules.v:32.17-32.26" *)  i_b[2];
  assign _0_[3] = i_a[3] &(* src = "MODEL/library_modules.v:32.17-32.26" *)  i_b[3];
  assign o_y[0] = ~(* src = "MODEL/library_modules.v:32.15-32.27" *) _0_[0];
  assign o_y[1] = ~(* src = "MODEL/library_modules.v:32.15-32.27" *) _0_[1];
  assign o_y[2] = ~(* src = "MODEL/library_modules.v:32.15-32.27" *) _0_[2];
  assign o_y[3] = ~(* src = "MODEL/library_modules.v:32.15-32.27" *) _0_[3];
  assign o_err = 1'h0;
  assign o_overflow = 1'h0;
endmodule

(* dynports =  1  *)
(* hdlname = "starting_ones" *)
(* src = "MODEL/library_modules.v:39.1-67.10" *)
module \$paramod\starting_ones\WIDTH=s32'00000000000000000000000000000100 (i_a, i_b, o_y, o_overflow, o_err);
  (* src = "MODEL/library_modules.v:43.35-43.38" *)
  input [3:0] i_a;
  wire [3:0] i_a;
  (* src = "MODEL/library_modules.v:44.35-44.38" *)
  input [3:0] i_b;
  wire [3:0] i_b;
  (* src = "MODEL/library_modules.v:45.35-45.38" *)
  output [3:0] o_y;
  wire [3:0] o_y;
  (* src = "MODEL/library_modules.v:46.35-46.45" *)
  output o_overflow;
  wire o_overflow;
  (* src = "MODEL/library_modules.v:47.35-47.40" *)
  output o_err;
  wire o_err;
  wire [15:0] _000_;
  wire [7:0] _001_;
  wire [3:0] _002_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _003_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [31:0] _004_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _005_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [31:0] _008_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _009_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [31:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [31:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [31:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [31:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [31:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [31:0] _030_;
  wire _031_;
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _032_;
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _033_;
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _034_;
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _035_;
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _036_;
  (* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _037_;
  (* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _038_;
  (* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _039_;
  (* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _040_;
  (* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _041_;
  (* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _042_;
  (* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _043_;
  (* src = "MODEL/library_modules.v:49.27-49.28" *)
  wire [7:0] c;
  (* src = "MODEL/library_modules.v:51.13-51.18" *)
  wire [31:0] count;
  (* src = "MODEL/library_modules.v:50.13-50.14" *)
  wire [31:0] i;
  assign _003_[0] = ~i_b[3];
  assign _026_[0] = ~_024_[0];
  assign _029_[4] = ~count[4];
  assign _029_[5] = ~count[5];
  assign _029_[6] = ~count[6];
  assign _029_[7] = ~count[7];
  assign _030_[31] = ~_028_[31];
  assign _007_[1] = _004_[1] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _004_[0];
  assign _011_[1] = _008_[1] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _008_[0];
  assign _011_[2] = _008_[2] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _009_[1];
  assign _015_[1] = _012_[1] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _012_[0];
  assign _015_[2] = _012_[2] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _013_[1];
  assign _015_[3] = _012_[3] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _013_[2];
  assign _019_[1] = _016_[1] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _016_[0];
  assign _019_[2] = _016_[2] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _017_[1];
  assign _019_[3] = _016_[3] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _017_[2];
  assign _019_[4] = _016_[4] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _017_[3];
  assign _023_[1] = _020_[1] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _020_[0];
  assign _023_[2] = _020_[2] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _021_[1];
  assign _023_[3] = _020_[3] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _021_[2];
  assign _023_[4] = _020_[4] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _021_[3];
  assign _023_[5] = _020_[5] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _021_[4];
  assign _027_[1] = _024_[1] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _024_[0];
  assign _027_[2] = _024_[2] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _025_[1];
  assign _027_[3] = _024_[3] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _025_[2];
  assign _027_[4] = _024_[4] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _025_[3];
  assign _027_[5] = _024_[5] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _025_[4];
  assign _027_[6] = _024_[6] ^(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _025_[5];
  assign _005_[1] = _004_[1] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _004_[0];
  assign _009_[1] = _008_[1] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _008_[0];
  assign _009_[2] = _008_[2] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _009_[1];
  assign _013_[1] = _012_[1] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _012_[0];
  assign _013_[3] = _032_ &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _013_[1];
  assign _032_ = _012_[3] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _012_[2];
  assign _013_[2] = _012_[2] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _013_[1];
  assign _017_[1] = _016_[1] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _016_[0];
  assign _017_[3] = _033_ &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _017_[1];
  assign _033_ = _016_[3] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _016_[2];
  assign _017_[2] = _016_[2] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _017_[1];
  assign _017_[4] = _016_[4] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _017_[3];
  assign _021_[1] = _020_[1] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _020_[0];
  assign _021_[3] = _034_ &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _021_[1];
  assign _034_ = _020_[3] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _020_[2];
  assign _035_ = _020_[5] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _020_[4];
  assign _021_[5] = _035_ &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _021_[3];
  assign _021_[2] = _020_[2] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _021_[1];
  assign _021_[4] = _020_[4] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _021_[3];
  assign _025_[1] = _024_[1] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _024_[0];
  assign _025_[3] = _036_ &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _025_[1];
  assign _036_ = _024_[3] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _024_[2];
  assign _037_ = _024_[5] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _024_[4];
  assign _025_[5] = _037_ &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _025_[3];
  assign _025_[2] = _024_[2] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _025_[1];
  assign _025_[4] = _024_[4] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _025_[3];
  assign _025_[6] = _024_[6] &(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _025_[5];
  assign _038_ = _029_[5] &(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[4];
  assign _039_ = _029_[7] &(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[6];
  assign _028_[3] = _000_[1] &(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _028_[1];
  assign _040_ = _000_[3] &(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_;
  assign _000_[2] = _029_[5] &(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _029_[4];
  assign _000_[3] = _029_[7] &(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _029_[6];
  assign _001_[1] = _000_[3] &(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _000_[2];
  assign _041_ = count[5] |(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _038_;
  assign _042_ = count[7] |(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _039_;
  assign _043_ = _042_ |(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _040_;
  assign _028_[31] = _043_ |(* src = "MODEL/library_modules.v:63.23-63.43|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _002_[0];
  assign _031_ = _030_[31] | _002_[0];
  assign _028_[1] = count[0] &(* src = "MODEL/library_modules.v:63.23-63.43" *)  count[1];
  assign _000_[1] = count[2] &(* src = "MODEL/library_modules.v:63.23-63.43" *)  count[3];
  assign _002_[0] = _028_[3] &(* src = "MODEL/library_modules.v:63.23-63.43" *)  _001_[1];
  assign _004_[0] = i_b[2] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _003_[0] : i_b[3];
  assign _004_[1] = i_b[2] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) i_b[3] : 1'h0;
  assign count[0] = i_a[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _026_[0] : _024_[0];
  assign count[1] = i_a[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _027_[1] : _024_[1];
  assign count[2] = i_a[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _027_[2] : _024_[2];
  assign count[3] = i_a[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _027_[3] : _024_[3];
  assign count[4] = i_a[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _027_[4] : _024_[4];
  assign count[5] = i_a[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _027_[5] : _024_[5];
  assign count[6] = i_a[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _027_[6] : _024_[6];
  assign count[7] = i_a[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _025_[6] : 1'h0;
  assign _008_[0] = i_b[1] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _006_[0] : _004_[0];
  assign _008_[1] = i_b[1] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _007_[1] : _004_[1];
  assign _008_[2] = i_b[1] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _005_[1] : 1'h0;
  assign _012_[0] = i_b[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _010_[0] : _008_[0];
  assign _012_[1] = i_b[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _011_[1] : _008_[1];
  assign _012_[2] = i_b[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _011_[2] : _008_[2];
  assign _012_[3] = i_b[0] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _009_[2] : 1'h0;
  assign _016_[0] = i_a[3] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _014_[0] : _012_[0];
  assign _016_[1] = i_a[3] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _015_[1] : _012_[1];
  assign _016_[2] = i_a[3] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _015_[2] : _012_[2];
  assign _016_[3] = i_a[3] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _015_[3] : _012_[3];
  assign _016_[4] = i_a[3] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _013_[3] : 1'h0;
  assign _020_[0] = i_a[2] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _018_[0] : _016_[0];
  assign _020_[1] = i_a[2] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _019_[1] : _016_[1];
  assign _020_[2] = i_a[2] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _019_[2] : _016_[2];
  assign _020_[3] = i_a[2] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _019_[3] : _016_[3];
  assign _020_[4] = i_a[2] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _019_[4] : _016_[4];
  assign _020_[5] = i_a[2] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _017_[4] : 1'h0;
  assign _024_[0] = i_a[1] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _022_[0] : _020_[0];
  assign _024_[1] = i_a[1] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _023_[1] : _020_[1];
  assign _024_[2] = i_a[1] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _023_[2] : _020_[2];
  assign _024_[3] = i_a[1] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _023_[3] : _020_[3];
  assign _024_[4] = i_a[1] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _023_[4] : _020_[4];
  assign _024_[5] = i_a[1] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _023_[5] : _020_[5];
  assign _024_[6] = i_a[1] ? (* src = "MODEL/library_modules.v:59.17-59.26|MODEL/library_modules.v:59.13-60.35" *) _021_[5] : 1'h0;
  assign _006_[0] = ~(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) _004_[0];
  assign _010_[0] = ~(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) _008_[0];
  assign _014_[0] = ~(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) _012_[0];
  assign _018_[0] = ~(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) _016_[0];
  assign _022_[0] = ~(* src = "MODEL/library_modules.v:60.25-60.34|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) _020_[0];
  assign o_overflow = ~(* src = "MODEL/library_modules.v:63.23-63.43" *) _031_;
  assign { _000_[15:4], _000_[0] } = { 12'hfff, _028_[1] };
  assign { _001_[7:2], _001_[0] } = { 6'h3f, _028_[3] };
  assign _002_[3:1] = 3'h7;
  assign _003_[31:1] = 31'h00000000;
  assign _004_[31:2] = 30'h00000000;
  assign { _005_[31:2], _005_[0] } = { 30'h00000000, _004_[0] };
  assign _006_[31:1] = { 30'h00000000, _004_[1] };
  assign { _007_[31:2], _007_[0] } = { 29'h00000000, _005_[1], _006_[0] };
  assign _008_[31:3] = 29'h00000000;
  assign { _009_[31:3], _009_[0] } = { 29'h00000000, _008_[0] };
  assign _010_[31:1] = { 29'h00000000, _008_[2:1] };
  assign { _011_[31:3], _011_[0] } = { 28'h0000000, _009_[2], _010_[0] };
  assign _012_[31:4] = 28'h0000000;
  assign { _013_[31:4], _013_[0] } = { 28'h0000000, _012_[0] };
  assign _014_[31:1] = { 28'h0000000, _012_[3:1] };
  assign { _015_[31:4], _015_[0] } = { 27'h0000000, _013_[3], _014_[0] };
  assign _016_[31:5] = 27'h0000000;
  assign { _017_[31:5], _017_[0] } = { 27'h0000000, _016_[0] };
  assign _018_[31:1] = { 27'h0000000, _016_[4:1] };
  assign { _019_[31:5], _019_[0] } = { 26'h0000000, _017_[4], _018_[0] };
  assign _020_[31:6] = 26'h0000000;
  assign { _021_[31:6], _021_[0] } = { 26'h0000000, _020_[0] };
  assign _022_[31:1] = { 26'h0000000, _020_[5:1] };
  assign { _023_[31:6], _023_[0] } = { 25'h0000000, _021_[5], _022_[0] };
  assign _024_[31:7] = 25'h0000000;
  assign { _025_[31:7], _025_[0] } = { 25'h0000000, _024_[0] };
  assign _026_[31:1] = { 25'h0000000, _024_[6:1] };
  assign { _027_[31:7], _027_[0] } = { 24'h000000, _025_[6], _026_[0] };
  assign { _028_[30:7], _028_[0] } = { _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], _028_[31], count[0] };
  assign { _029_[31:8], _029_[3:0] } = { 24'hffffff, count[3:0] };
  assign _030_[30:8] = { _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31], _030_[31] };
  assign c = { i_b, i_a };
  assign count[31:8] = 24'h000000;
  assign i = 32'd4294967295;
  assign o_err = 1'h0;
  assign o_y = count[3:0];
endmodule

(* dynports =  1  *)
(* hdlname = "subtractor" *)
(* src = "MODEL/library_modules.v:2.1-18.10" *)
module \$paramod\subtractor\WIDTH=s32'00000000000000000000000000000100 (i_a, i_b, o_y, o_overflow, o_err);
  (* src = "MODEL/library_modules.v:6.35-6.38" *)
  input [3:0] i_a;
  wire [3:0] i_a;
  (* src = "MODEL/library_modules.v:7.35-7.38" *)
  input [3:0] i_b;
  wire [3:0] i_b;
  (* src = "MODEL/library_modules.v:8.35-8.38" *)
  output [3:0] o_y;
  wire [3:0] o_y;
  (* src = "MODEL/library_modules.v:9.35-9.45" *)
  output o_overflow;
  wire o_overflow;
  (* src = "MODEL/library_modules.v:10.35-10.40" *)
  output o_err;
  wire o_err;
  wire _00_;
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [3:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _03_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _04_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  (* unused_bits = "3" *)
  wire [3:0] _05_;
  (* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _06_;
  (* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _07_;
  assign o_y[0] = ~_04_[0];
  assign _00_ = i_a[3] ^(* src = "MODEL/library_modules.v:15.23-15.51" *)  i_b[3];
  assign _01_ = i_a[3] ^(* src = "MODEL/library_modules.v:15.57-15.85" *)  o_y[3];
  assign o_y[1] = _04_[1] ^(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _03_[0];
  assign o_y[2] = _04_[2] ^(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _03_[1];
  assign o_y[3] = _04_[3] ^(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _03_[2];
  assign _05_[0] = i_a[0] &(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _02_[0];
  assign _05_[1] = i_a[1] &(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _02_[1];
  assign _05_[2] = i_a[2] &(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _02_[2];
  assign _04_[0] = i_a[0] ^(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _02_[0];
  assign _04_[1] = i_a[1] ^(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _02_[1];
  assign _04_[2] = i_a[2] ^(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _02_[2];
  assign _04_[3] = i_a[3] ^(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _02_[3];
  assign _06_ = _04_[1] &(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _03_[0];
  assign _07_ = _04_[2] &(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _03_[1];
  assign _03_[0] = _05_[0] |(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:231.10-231.28" *)  _04_[0];
  assign _03_[1] = _05_[1] |(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _06_;
  assign _03_[2] = _05_[2] |(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _07_;
  assign o_overflow = _00_ &(* src = "MODEL/library_modules.v:15.22-15.86" *)  _01_;
  assign _02_[0] = ~(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) i_b[0];
  assign _02_[1] = ~(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) i_b[1];
  assign _02_[2] = ~(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) i_b[2];
  assign _02_[3] = ~(* src = "MODEL/library_modules.v:13.15-13.24|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) i_b[3];
  assign o_err = 1'h0;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "MODEL/top.v:1.1-99.10" *)
module TOP(i_arg0, i_arg1, i_oper, i_clk, i_rstn, o_flag, o_result);
  (* src = "MODEL/top.v:6.33-6.39" *)
  input [3:0] i_arg0;
  wire [3:0] i_arg0;
  (* src = "MODEL/top.v:7.33-7.39" *)
  input [3:0] i_arg1;
  wire [3:0] i_arg1;
  (* src = "MODEL/top.v:8.33-8.39" *)
  input [1:0] i_oper;
  wire [1:0] i_oper;
  (* src = "MODEL/top.v:9.33-9.38" *)
  input i_clk;
  wire i_clk;
  (* src = "MODEL/top.v:10.33-10.39" *)
  input i_rstn;
  wire i_rstn;
  (* src = "MODEL/top.v:11.33-11.39" *)
  output [3:0] o_flag;
  wire [3:0] o_flag;
  (* src = "MODEL/top.v:12.33-12.41" *)
  output [3:0] o_result;
  wire [3:0] o_result;
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire [1:0] _03_;
  wire [1:0] _04_;
  wire [1:0] _05_;
  wire [1:0] _06_;
  wire [1:0] _07_;
  wire [1:0] _08_;
  wire [1:0] _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "MODEL/top.v:90.38-90.51" *)
  wire _14_;
  (* src = "MODEL/top.v:90.16-90.34" *)
  wire _15_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:591.28-591.35" *)
  wire [3:0] _16_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:581.22-581.23" *)
  wire [3:0] _17_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:586.19-586.22" *)
  wire [0:0] _18_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:591.28-591.35" *)
  wire [3:0] _19_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:586.19-586.22" *)
  wire [0:0] _20_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:591.28-591.35" *)
  wire [15:0] _21_;
  (* force_downto = 32'd1 *)
  (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:586.19-586.22" *)
  wire [3:0] _22_;
  (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.15" *)
  wire _23_;
  (* src = "MODEL/top.v:19.28-19.39" *)
  wire decoder_err;
  (* src = "MODEL/top.v:19.10-19.26" *)
  wire decoder_overflow;
  (* src = "MODEL/top.v:15.58-15.72" *)
  wire [3:0] decoder_result;
  (* src = "MODEL/top.v:17.25-17.33" *)
  wire nand_err;
  (* src = "MODEL/top.v:17.10-17.23" *)
  wire nand_overflow;
  (* src = "MODEL/top.v:15.34-15.45" *)
  wire [3:0] nand_result;
  (* src = "MODEL/top.v:18.23-18.29" *)
  wire oh_err;
  (* src = "MODEL/top.v:18.10-18.21" *)
  wire oh_overflow;
  (* src = "MODEL/top.v:15.47-15.56" *)
  wire [3:0] oh_result;
  (* src = "MODEL/top.v:16.24-16.31" *)
  wire sub_err;
  (* src = "MODEL/top.v:16.10-16.22" *)
  wire sub_overflow;
  (* src = "MODEL/top.v:15.22-15.32" *)
  wire [3:0] sub_result;
  (* src = "MODEL/top.v:60.24-60.32" *)
  wire temp_err;
  (* src = "MODEL/top.v:60.34-60.42" *)
  wire temp_neg;
  (* src = "MODEL/top.v:60.9-60.22" *)
  wire temp_overflow;
  (* src = "MODEL/top.v:60.44-60.52" *)
  wire temp_pos;
  assign _01_ = ~i_oper[1];
  assign _00_ = ~i_oper[0];
  assign temp_pos = _15_ &(* src = "MODEL/top.v:90.16-90.52" *)  _14_;
  assign temp_neg = o_result[3] &(* src = "MODEL/top.v:91.16-91.51" *)  _14_;
  assign _16_[3] = sub_err &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[3];
  assign _16_[2] = nand_err &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[2];
  assign _16_[1] = oh_err &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[1];
  assign _16_[0] = decoder_err &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[0];
  assign _19_[3] = sub_overflow &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[3];
  assign _19_[2] = nand_overflow &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[2];
  assign _19_[1] = oh_overflow &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[1];
  assign _19_[0] = decoder_overflow &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[0];
  assign _21_[12] = sub_result[0] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[3];
  assign _21_[13] = sub_result[1] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[3];
  assign _21_[14] = sub_result[2] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[3];
  assign _21_[15] = sub_result[3] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[3];
  assign _21_[8] = nand_result[0] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[2];
  assign _21_[9] = nand_result[1] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[2];
  assign _21_[10] = nand_result[2] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[2];
  assign _21_[11] = nand_result[3] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[2];
  assign _21_[4] = oh_result[0] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[1];
  assign _21_[5] = oh_result[1] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[1];
  assign _21_[6] = oh_result[2] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[1];
  assign _21_[7] = oh_result[3] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[1];
  assign _21_[0] = decoder_result[0] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[0];
  assign _21_[1] = decoder_result[1] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[0];
  assign _21_[2] = decoder_result[2] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[0];
  assign _21_[3] = decoder_result[3] &(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:593.44-593.84" *)  _17_[0];
  assign _11_ = _00_ |(* src = "MODEL/top.v:73.16-73.16|MODEL/top.v:68.9-89.16" *)  i_oper[1];
  assign _12_ = i_oper[0] |(* src = "MODEL/top.v:78.16-78.16|MODEL/top.v:68.9-89.16" *)  _01_;
  assign _13_ = _00_ |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16" *)  _01_;
  assign _02_[0] = o_result[0] |(* src = "MODEL/top.v:91.37-91.50" *)  o_result[1];
  assign _02_[1] = o_result[2] |(* src = "MODEL/top.v:91.37-91.50" *)  o_result[3];
  assign _14_ = _02_[0] |(* src = "MODEL/top.v:91.37-91.50" *)  _02_[1];
  assign _03_[0] = _16_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _16_[1];
  assign _03_[1] = _16_[2] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _16_[3];
  assign _18_ = _03_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _03_[1];
  assign _23_ = _04_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.15" *)  _04_[1];
  assign _05_[0] = _19_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _19_[1];
  assign _05_[1] = _19_[2] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _19_[3];
  assign _20_ = _05_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _05_[1];
  assign _04_[0] = _17_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.15" *)  _17_[1];
  assign _04_[1] = _17_[2] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.15" *)  _17_[3];
  assign _06_[0] = _21_[3] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _21_[7];
  assign _06_[1] = _21_[11] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _21_[15];
  assign _22_[3] = _06_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _06_[1];
  assign _07_[0] = _21_[2] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _21_[6];
  assign _07_[1] = _21_[10] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _21_[14];
  assign _22_[2] = _07_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _07_[1];
  assign _08_[0] = _21_[1] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _21_[5];
  assign _08_[1] = _21_[9] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _21_[13];
  assign _22_[1] = _08_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _08_[1];
  assign _09_[0] = _21_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _21_[4];
  assign _09_[1] = _21_[8] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _21_[12];
  assign _22_[0] = _09_[0] |(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:601.20-601.31" *)  _09_[1];
  assign _10_ = i_oper[0] |(* src = "MODEL/top.v:68.21-68.21|MODEL/top.v:68.9-89.16" *)  i_oper[1];
  assign _17_[3] = ~(* src = "MODEL/top.v:68.21-68.21|MODEL/top.v:68.9-89.16" *) _10_;
  assign _17_[2] = ~(* src = "MODEL/top.v:73.16-73.16|MODEL/top.v:68.9-89.16" *) _11_;
  assign _17_[1] = ~(* src = "MODEL/top.v:78.16-78.16|MODEL/top.v:68.9-89.16" *) _12_;
  assign _17_[0] = ~(* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16" *) _13_;
  assign temp_err = _23_ ? (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.25" *) _18_ : 1'hx;
  assign temp_overflow = _23_ ? (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.25" *) _20_ : 1'hx;
  assign o_result[0] = _23_ ? (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.25" *) _22_[0] : 1'hx;
  assign o_result[1] = _23_ ? (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.25" *) _22_[1] : 1'hx;
  assign o_result[2] = _23_ ? (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.25" *) _22_[2] : 1'hx;
  assign o_result[3] = _23_ ? (* src = "MODEL/top.v:83.16-83.16|MODEL/top.v:68.9-89.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.25" *) _22_[3] : 1'hx;
  assign _15_ = ~(* src = "MODEL/top.v:90.16-90.34" *) o_result[3];
  (* src = "MODEL/top.v:50.5-57.6" *)
  \$paramod$a9c22756d9a8dd0110c8c717d10bd443a01d2637\onehot2u2_decoder  u_decoder (
    .i_a_oh(i_arg0[0]),
    .i_b_oh(i_arg1[0]),
    .o_err(decoder_err),
    .o_overflow(decoder_overflow),
    .o_y_u2(decoder_result)
  );
  (* src = "MODEL/top.v:32.5-39.6" *)
  \$paramod\nand_gate\WIDTH=s32'00000000000000000000000000000100  u_nand_gate (
    .i_a(i_arg0),
    .i_b(i_arg1),
    .o_err(nand_err),
    .o_overflow(nand_overflow),
    .o_y(nand_result)
  );
  (* src = "MODEL/top.v:41.5-48.6" *)
  \$paramod\starting_ones\WIDTH=s32'00000000000000000000000000000100  u_starting_ones (
    .i_a(i_arg0),
    .i_b(i_arg1),
    .o_err(oh_err),
    .o_overflow(oh_overflow),
    .o_y(oh_result)
  );
  (* src = "MODEL/top.v:23.5-30.6" *)
  \$paramod\subtractor\WIDTH=s32'00000000000000000000000000000100  u_subtractor (
    .i_a(i_arg0),
    .i_b(i_arg1),
    .o_err(sub_err),
    .o_overflow(sub_overflow),
    .o_y(sub_result)
  );
  assign o_flag = { temp_overflow, temp_pos, temp_neg, temp_err };
endmodule
